// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcBN4nOUHusPM7rDBpl9W0NJCC5UWd3Q',
    appId: '1:846787076887:web:8d44ab296fad431380cd52',
    messagingSenderId: '846787076887',
    projectId: 'nexus-d3a46',
    authDomain: 'nexus-d3a46.firebaseapp.com',
    storageBucket: 'nexus-d3a46.firebasestorage.app',
    measurementId: 'G-G5WTFTM3YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_JQIz10ZFzuX6-t4EEynQ-S2QtJXrhgo',
    appId: '1:846787076887:android:26aa0600066791e680cd52',
    messagingSenderId: '846787076887',
    projectId: 'nexus-d3a46',
    storageBucket: 'nexus-d3a46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69N6KWAqu-_Kyk5C-tJ6ifdBetk1WU1A',
    appId: '1:846787076887:ios:5fa9b44f4d7c6f8780cd52',
    messagingSenderId: '846787076887',
    projectId: 'nexus-d3a46',
    storageBucket: 'nexus-d3a46.firebasestorage.app',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC69N6KWAqu-_Kyk5C-tJ6ifdBetk1WU1A',
    appId: '1:846787076887:ios:5fa9b44f4d7c6f8780cd52',
    messagingSenderId: '846787076887',
    projectId: 'nexus-d3a46',
    storageBucket: 'nexus-d3a46.firebasestorage.app',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcBN4nOUHusPM7rDBpl9W0NJCC5UWd3Q',
    appId: '1:846787076887:web:8952cb81a3538ed280cd52',
    messagingSenderId: '846787076887',
    projectId: 'nexus-d3a46',
    authDomain: 'nexus-d3a46.firebaseapp.com',
    storageBucket: 'nexus-d3a46.firebasestorage.app',
    measurementId: 'G-CLTPCN1CVN',
  );
}
